### ISSUE TITLE
Anti aliasing issues 

### ISSUE THREAD

**Issue by Elodie-Praxinos** [Praxinos/ULIS#1]
[Screen Recording 2020-11-23 at 15.32.48.mp4.zip](https://github.com/Praxinos/ULIS/files/5583670/Screen.Recording.2020-11-23.at.15.32.48.mp4.zip)

**Comment by Clement-Praxinos** [comment]
Note to self: Rounding errors on Rect with negative coordinates for BlendAA ( check FMath::RoundToNegativeInfinity )
