### ISSUE TITLE
Variables are initialized through the call to the same function. It's probably an error.

### ISSUE THREAD

**Issue by thehlopster** [Praxinos/ULIS#2]
Variables are initialized through the call to the same function. It's probably an error.
[here](https://github.com/Praxinos/ULIS/blob/dev/source/Process/Misc/Alloc.cpp#L49)
I guess it should be changed from this
```cpp
auto w = block.Width();
auto h = block.Width();
```
to this
```cpp
auto w = block.Width();
auto h = block.Height();
```

**Comment by Clement-Praxinos** [comment]
Thanks for opening an issue and for the report, i overlooked it ! This is now fixed.
